# Generated by Django 4.0.1 on 2022-01-07 14:11

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, unique=True)),
                ('description', django_editorjs.fields.EditorJsField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
