# Generated by Django 4.0.1 on 2022-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_snippet_snippet_alter_snippet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
