# Generated by Django 4.0.1 on 2022-01-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_snippet_description_alter_snippet_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='snippet_body',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
