# Generated by Django 4.0.1 on 2022-01-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='extension',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
