# Generated by Django 4.0.1 on 2022-01-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_snippet_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='extension',
            new_name='snippet_language',
        ),
    ]
